version: '3'
tasks:
  default:
    cmds:
      - task -l
  ci:
    desc: "Run CI for all years"
    cmds:
      - python .github/workflows/ci.py > report.log
  inside:
    desc: "Run container with YEAR\\DAY\\LANGUAGE mounted"
    vars:
      YEAR: "AoC2023"
      DAY: "day_05_02"
      LANGUAGE: "python"
    cmds: 
      - docker build -t {{.LANGUAGE}}-temp ./images/{{.LANGUAGE}}
      - docker run -it -v $(pwd)\\{{.YEAR}}\\{{.DAY}}\\{{.LANGUAGE}}:/src -w / {{.LANGUAGE}}-temp bash
