name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.x
      - name: Install Dagger-IO
        run: python3 -m pip install dagger-io
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Dagger CLI
        run: curl -L https://dl.dagger.io/dagger/install.sh | sh && mkdir dist && ./bin/dagger run python .github/workflows/ci.py >> dist/result.log
      - name: Archive artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: dist/result.log
