name: Tests
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    outputs:
      REPORT: ${{ steps.dagger.outputs.report}}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.x
      - name: Install Dagger-IO
        run: python3 -m pip install dagger-io
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dagger CLI
        run: curl -L https://dl.dagger.io/dagger/install.sh | sh && mkdir dist
      - name: Run Dagger CLI
        id: dagger
        run: echo "report=$(./bin/dagger run python .github/workflows/ci.py)" >> "$GITHUB_OUTPUT"
      - name: Archive artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: dist/
  report:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - env:
          REPORT: ${{ needs.testing.outputs.REPORT }}
        run: echo "$REPORT"
    
