name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.x
      - name: Install Dagger-IO
        run: python3 -m pip install dagger-io
      - name: Install Dagger CLI
        run: curl -L https://dl.dagger.io/dagger/install.sh | sh
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Dagger CI
        run: ./bin/dagger run python .github/workflows/ci.py >> dist/result.log